name = "travel-planner-frontend"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "travel_planner_db"
database_id = "1f2a2fdd-fdc5-436b-905e-5d97dc2fbba8"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "ATTACHMENTS_BUCKET"
bucket_name = "travel-planner-attachments"

[alias]
"@libsql/client/node" = "./src/db/empty-alias.ts"
"@libsql/isomorphic-ws" = "./src/db/empty-alias.ts"
